### ISSUE TITLE
Use Socket.io and ship Meower Quickly

### ISSUE THREAD

**Issue by nodexninja** [meower-media-co/Meower-Website#22]
### Why are you guys using WebSockets?
Firstly, I don't know why Meower is not working right now, and I am guessing it's because the server is undergoing changes. Now, I heard this project has been going on for *ages* and hasn't been released properly yet with fully-functional features. I see you guys like to congest the app with python, but I know a way to get this social media platform off the ground quicker. **JavaScript** will do you guys a lot of good because you can:
- Build better UIs
- Create a server faster
- Get real time data updates with Socket.io
- Use **Vue**

I understand that some of you like python but trust me JavaScript is easier to work with and my friend William is a pretty good JavaScript developer.

> I'm also offering to work on the css of your website because it looks a bit rushed 😉

**Comment by catonmeower** [comment]
I'm not in the GitHub organization, but I can answer some of these things:
1. Meower was down because Mike's power cords broke while he was on vacation. Nothing he could do about that (but changes are being done for beta 6, but they're not released yet)
2. As of right now we are working on "new meower" which is basically recreating the entire thing which should solve these issues. The reason we still have this system is because our scope of the project has changed and it'll take a lot of time to recreate the entire thing

With Beta 6, the ability to use the API to post and do actions is being implemented, which the api is still python and websockets are still used for the main app, but it should be a step forward until the complete revamp that new meower will be.

**Comment by tnix100** [comment]
> 

Thanks for your comment! Addressing the downtime, it was due to Mike's fibre optic line being accidently cut while he was on vacation.

A project has been in the works for a little while now known as "New Meower", it's being done mainly by William Horning right now as others are still learning how to use the technology we're going to be using for New Meower and/or still working on legacy Meower.

New Meower is going to use basically everything you mentioned, Node.js for the server, mainly using a REST API instead of relying on WebSockets, Vue/Vite for the frontend, etc. 

New Meower is going to take a while though, and in the meantime we're working on Beta 6 which is going to start adding more features to the REST API and hopefully cleaning up Meower a bit. We'll also probably have a beta 7 which will continue to just clean things up and move more to API v0 (API v1 is for New Meower).


> Just curious, is your friend William, William Horning by any chance?

**Comment by nodexninja** [comment]
Yes I knew him for quite some time. He used to be a moderator with me in Scratch x Discord. Now I'm an admin in multiple servers, but we both knew JavaScript well.

**Comment by wgyt** [comment]
As @tnix100 pointed out, the New Meower project will be using Vue, Vite, Tailwind, SCSS, Typescript, and Javascript. 
Here's what I have to say about your bullet points (in order):
- this is part of New Meower's goal, and we have some mockups of UI which look much better than their Legacy Meower equivalents
- I highly doubt this is a benefit, but 🤷🏻 
- we probably won't be using socket.io, but rather be building our own websocket-based protocol for live updates that isn't related to our current tech stack
- this is part of the plan
