### ISSUE TITLE
New Design breaks "Classic Pages"

### ISSUE THREAD

**Issue by zedthehedgehog** [meower-media-co/Meower-Website#51]
Ever since the new design was merged with main, the "classic pages" such as customid and discord link pages don't work

**Comment by williamhorning** [comment]
@tnix100 intentionally deleted customid in https://github.com/meower-media-co/Meower-Website/commit/07fc4916cf479cfa60883e3ff40347948a5261d7, not sure why though

**Comment by tnix100** [comment]
> @tnix100 intentionally deleted customid in https://github.com/meower-media-co/Meower-Website/commit/07fc4916cf479cfa60883e3ff40347948a5261d7, not sure why though

1. It says "Beta 6" instead of CL4 port
2. We're using snowflake IDs instead of UUID4s, which with custom IDs will cause sorting and inconsistency issues (so we will need to reconsider allowing custom IDs)

**Comment by williamhorning** [comment]
@tnix100 why are we using Snowflakes? also, what sorting issues would they cause?

**Comment by tnix100** [comment]
> @tnix100 why are we using Snowflakes? also, what sorting issues would they cause?

1. Way shorter than object IDs or UUID4s
2. Look much better than UUID4s (imo)
3. Item can be sorted by them
4. Can know when they were generated
5. Can know what server they were generated on (may be useful when testing multiple nodes)

Some things sort by _id (because sometimes I need _id within a compound index anyway for range, so less memory usage not having to also index the item's time field).

**Comment by tnix100** [comment]
Not an issue with new design by DaCatBlock.
